//Domain
export const DOMAIN = "http://192.168.31.209:8080/api/";

//Auth contanst


//Login
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCSESS = "LOGIN_SUCCSESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

//Test
export const TEST_REQUEST = "TEST_REQUEST";
export const TEST_SUCCSESS = "TEST_SUCCSESS";
export const TEST_FAILURE = "TEST_FAILURE";


//Post
export const CREATE_POST_REQUEST = "CREATE_POST_REQUEST";
export const CREATE_POST_SUCCSESS = "CREATE_POST_SUCCSESS";
export const CREATE_POST_FAILURE = "CREATE_POST_FAILURE";

export const UPDATE_POST_REQUEST = "UPDATE_POST_REQUEST";
export const UPDATE_POST_SUCCSESS = "UPDATE_POST_SUCCSESS";
export const UPDATE_POST_FAILURE = "UPDATE_POST_FAILURE";

export const DELETE_POST_REQUEST = "DELETE_POST_REQUEST";
export const DELETE_POST_SUCCSESS = "DELETE_POST_SUCCSESS";
export const DELETE_POST_FAILURE = "DELETE_POST_FAILURE";

export const GET_POST_REQUEST = "GET_POST_REQUEST";
export const GET_POST_SUCCSESS = "GET_POST_SUCCSESS";
export const GET_POST_FAILURE = "GET_POST_FAILURE";